server:
  port: 9002
  shutdown: graceful
  netty:
    connection-timeout: 2s
    idle-timeout: 15s

spring:
  application:
    name: order-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  output:
    ansi:
      enabled: always
  r2dbc:
    username: user
    password: password
    url: r2dbc:postgresql://localhost:5432/bookshop_order
    pool:
      max-create-connection-time: 2s
      initial-size: 5
      max-size: 10
  sql:
    init:
      mode: always


bookshop:
  catalog-service-uri: "http://localhost:9001"
