server:
  port: 9002
  shutdown: graceful
  netty:
    connection-timeout: 2s
    idle-timeout: 15s


management:
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: order-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  output:
    ansi:
      enabled: always
  r2dbc:
    username: user
    password: password
    url: r2dbc:postgresql://localhost:5432/bookshop_order
    pool:
      max-create-connection-time: 2s
      initial-size: 5
      max-size: 10
  sql:
    init:
      mode: always
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
tracing:
    url: http://localhost:4318/v1/traces
bookshop:
  catalog-service-uri: "http://localhost:9001"
